name: Deploy App to Azure App Service

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Upload Jar File
      uses: actions/upload-artifact@v4.3.6
      with:
        # Artifact name
        name: springboot-example
        path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.0
      with:
        # Name of the Azure Web App
        app-name: springboot-hello-api
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: '*.jar'
